export const FETCH_SITES_REQUESTED = "FETCH_SITES_REQUESTED";
export const FETCH_SITES_SUCCESS = "FETCH_SITES_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const SORT_BY = "SORT_BY";
